# Generated by Django 4.2.4 on 2023-08-12 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='locationcategorymodel',
            name='description',
        ),
        migrations.RemoveField(
            model_name='personmodel',
            name='location',
        ),
        migrations.RemoveField(
            model_name='persontypemodel',
            name='description',
        ),
        migrations.AlterField(
            model_name='personmodel',
            name='photo',
            field=models.ImageField(default='', upload_to='person'),
            preserve_default=False,
        ),
    ]
