# Generated by Django 4.2.3 on 2023-08-05 01:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='locationmodel',
            old_name='type',
            new_name='loc_type',
        ),
    ]
