# Generated by Django 4.2.4 on 2023-08-12 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_locationcategorymodel_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personmodel',
            name='type',
        ),
        migrations.AddField(
            model_name='personmodel',
            name='category',
            field=models.ManyToManyField(to='app.persontypemodel'),
        ),
    ]
