# Generated by Django 4.2.3 on 2023-08-05 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0003_remove_personvisitmodel_person'),
        ('app', '0003_rename_loc_type_locationmodel_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personmodel',
            name='type',
        ),
        migrations.DeleteModel(
            name='PersonTypeModel',
        ),
        migrations.DeleteModel(
            name='PersonModel',
        ),
    ]
