# Generated by Django 4.2.4 on 2023-08-12 11:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_addeditmodel_chaing_id'),
        ('app', '0003_remove_personmodel_type_personmodel_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='personmodel',
            name='beat',
            field=models.ForeignKey(default='1391ea0c-d974-42be-bf42-002efc2944b1', on_delete=django.db.models.deletion.CASCADE, related_name='person_in_ba', to='authentication.beatareamodel'),
            preserve_default=False,
        ),
    ]
