# Generated by Django 4.2.4 on 2023-08-12 11:49

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0007_delete_addeditmodel'),
        ('app', '0004_personmodel_beat'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddEditModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('approval_type', models.CharField(choices=[('LOCATION', 'Location'), ('PERSON', 'Person')], max_length=12)),
                ('approval_status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default=('PENDING', 'Pending'), max_length=12)),
                ('chaing_id', models.CharField(blank=True, max_length=50, null=True)),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('category', models.CharField(blank=True, max_length=50, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='approvals')),
                ('incharge_name', models.CharField(blank=True, max_length=50, null=True)),
                ('incharge_contact', models.CharField(blank=True, max_length=50, null=True)),
                ('incharge_description', models.CharField(blank=True, max_length=50, null=True)),
                ('BO', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='bo_req', to='authentication.beatofficermodel')),
            ],
            options={
                'db_table': 'approval_requests',
            },
        ),
    ]
