# Generated by Django 4.2.3 on 2023-08-12 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_rename_contact_locationinchargemodel_incharge_contact_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='locationinchargemodel',
            old_name='incharge_contact',
            new_name='contact',
        ),
        migrations.RenameField(
            model_name='locationinchargemodel',
            old_name='incharge_description',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='locationinchargemodel',
            old_name='incharge_name',
            new_name='name',
        ),
    ]
