# Generated by Django 4.2.4 on 2023-08-16 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_todomodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personmodel',
            name='category',
        ),
        migrations.AddField(
            model_name='personmodel',
            name='arm_licenses',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='personmodel',
            name='bad_character',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='personmodel',
            name='budding_criminals',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='personmodel',
            name='criminal_of_known_areas',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='personmodel',
            name='externee_more_than_2_crimes',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='personmodel',
            name='proclaimed_offenders',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='personmodel',
            name='senior_citizen',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='personmodel',
            name='suspected_brothels',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='PersonTypeModel',
        ),
    ]
