# Generated by Django 4.2.4 on 2023-08-16 05:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_remove_personmodel_category_personmodel_arm_licenses_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TodoModel',
        ),
    ]
