# Generated by Django 4.2.3 on 2023-08-16 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_delete_todomodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personmodel',
            name='arm_licenses',
        ),
        migrations.RemoveField(
            model_name='personmodel',
            name='bad_character',
        ),
        migrations.RemoveField(
            model_name='personmodel',
            name='beat',
        ),
        migrations.RemoveField(
            model_name='personmodel',
            name='budding_criminals',
        ),
        migrations.RemoveField(
            model_name='personmodel',
            name='criminal_of_known_areas',
        ),
        migrations.RemoveField(
            model_name='personmodel',
            name='externee_more_than_2_crimes',
        ),
        migrations.RemoveField(
            model_name='personmodel',
            name='proclaimed_offenders',
        ),
        migrations.RemoveField(
            model_name='personmodel',
            name='senior_citizen',
        ),
        migrations.RemoveField(
            model_name='personmodel',
            name='suspected_brothels',
        ),
    ]
