# Generated by Django 4.2.3 on 2023-08-16 16:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0008_beatofficermodel_tid'),
        ('app', '0009_remove_personmodel_arm_licenses_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='personmodel',
            name='arm_licenses',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='personmodel',
            name='bad_character',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='personmodel',
            name='beat',
            field=models.ForeignKey(default='1391ea0c-d974-42be-bf42-002efc2944b1', on_delete=django.db.models.deletion.CASCADE, related_name='person_in_ba', to='authentication.beatareamodel'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='personmodel',
            name='budding_criminals',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='personmodel',
            name='criminal_of_known_areas',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='personmodel',
            name='externee_more_than_2_crimes',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='personmodel',
            name='proclaimed_offenders',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='personmodel',
            name='senior_citizen',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='personmodel',
            name='suspected_brothels',
            field=models.BooleanField(default=False),
        ),
    ]
