# Generated by Django 4.2.3 on 2023-08-17 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_addeditlocationmodel_addeditpersonmodel_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addeditpersonmodel',
            name='arm_licenses',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='addeditpersonmodel',
            name='bad_character',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='addeditpersonmodel',
            name='budding_criminals',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='addeditpersonmodel',
            name='criminal_of_known_areas',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='addeditpersonmodel',
            name='externee_more_than_2_crimes',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='addeditpersonmodel',
            name='proclaimed_offenders',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='addeditpersonmodel',
            name='senior_citizen',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='addeditpersonmodel',
            name='suspected_brothels',
            field=models.BooleanField(default=False),
        ),
    ]
