# Generated by Django 4.2.4 on 2023-08-03 12:28

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app', '0001_initial'),
        ('authentication', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoactionVisit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('audio', models.FileField(blank=True, null=True, upload_to='audio')),
                ('comments', models.TextField(blank=True, null=True)),
                ('img', models.ImageField(blank=True, null=True, upload_to='location_visit')),
                ('situation', models.FloatField(default=5.0, validators=[django.core.validators.MaxValueValidator(10.0), django.core.validators.MinValueValidator(0.0)])),
                ('report_id', models.CharField(max_length=50)),
                ('BO', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bo_report', to='authentication.beatofficermodel')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.locationmodel')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
