# Generated by Django 4.2.4 on 2023-08-12 06:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_alter_summonwarrentmodel_visted_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='generalvisitmodel',
            name='situation',
            field=models.FloatField(default=5.0, validators=[django.core.validators.MaxValueValidator(10.0), django.core.validators.MinValueValidator(1.0)]),
        ),
        migrations.AddField(
            model_name='personvisitmodel',
            name='situation',
            field=models.FloatField(default=5.0, validators=[django.core.validators.MaxValueValidator(10.0), django.core.validators.MinValueValidator(1.0)]),
        ),
        migrations.AlterField(
            model_name='loactionvisitmodel',
            name='situation',
            field=models.FloatField(default=5.0, validators=[django.core.validators.MaxValueValidator(10.0), django.core.validators.MinValueValidator(1.0)]),
        ),
        migrations.AlterField(
            model_name='summonwarrentmodel',
            name='category',
            field=models.CharField(choices=[('NOTICE', 'Notice'), ('SUMMON', 'Summon'), ('WARRENT', 'Warrent')], max_length=50),
        ),
    ]
