# Generated by Django 4.2.3 on 2023-08-05 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_beatofficerlogs_generalvisitmodel_loactionvisitmodel_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personvisitmodel',
            name='person',
        ),
    ]
