# Generated by Django 4.2.4 on 2023-08-12 08:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_addeditmodel_chaing_id'),
        ('reports', '0003_generalvisitmodel_situation_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='summonwarrentmodel',
            name='is_visited',
        ),
        migrations.AddField(
            model_name='summonwarrentmodel',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='summonwarrentmodel',
            name='done_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='bo_summ', to='authentication.beatofficermodel'),
        ),
        migrations.AddField(
            model_name='summonwarrentmodel',
            name='order_name',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='summonwarrentmodel',
            name='order_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('SERVED', 'Served'), ('UNSERVED', 'Unserved')], default='PENDING', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='summonwarrentmodel',
            name='photo',
            field=models.ImageField(default='', upload_to='order'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='summonwarrentmodel',
            name='assigned_to',
        ),
        migrations.AlterField(
            model_name='summonwarrentmodel',
            name='category',
            field=models.CharField(choices=[('NOTICE', 'Notice'), ('SUMMON', 'Summon'), ('WARRENT', 'Warrent')], max_length=10),
        ),
        migrations.AlterModelTable(
            name='summonwarrentmodel',
            table='court_orders',
        ),
        migrations.DeleteModel(
            name='GeneralVisitModel',
        ),
        migrations.AddField(
            model_name='summonwarrentmodel',
            name='assigned_to',
            field=models.ManyToManyField(to='authentication.beatofficermodel'),
        ),
    ]
