# Generated by Django 4.2.3 on 2023-08-16 15:43

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0008_beatofficermodel_tid'),
        ('reports', '0004_remove_summonwarrentmodel_is_visited_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProclaimationModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('order_id', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=50)),
                ('due_date', models.DateField()),
            ],
            options={
                'db_table': 'proclaimation',
            },
        ),
        migrations.RenameModel(
            old_name='SummonWarrentModel',
            new_name='CourtOrderModel',
        ),
        migrations.CreateModel(
            name='ProclaimaitonImagesModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('img', models.ImageField(upload_to='proclaimation')),
                ('proclaimation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proclaimation_images', to='reports.proclaimationmodel')),
            ],
            options={
                'db_table': 'proclaimation_images',
            },
        ),
    ]
