# Generated by Django 4.2.3 on 2023-08-07 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0005_personvisitmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generalvisitmodel',
            name='visit_id',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='loactionvisitmodel',
            name='visit_id',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='personvisitmodel',
            name='visit_id',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
