# Generated by Django 4.2.3 on 2023-08-09 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0007_alter_summonwarrentmodel_visted_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='summonwarrentmodel',
            name='name',
            field=models.CharField(default='ab', max_length=50),
            preserve_default=False,
        ),
    ]
