# Generated by Django 4.2.3 on 2023-08-11 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0008_summonwarrentmodel_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loactionvisitmodel',
            name='BO',
        ),
    ]
