# Generated by Django 4.2.3 on 2023-08-11 13:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_beatofficermodel_beat_area'),
        ('reports', '0011_remove_loactionvisitmodel_bo'),
    ]

    operations = [
        migrations.AddField(
            model_name='loactionvisitmodel',
            name='BO',
            field=models.ForeignKey(default='6adfbecc-d790-4e9d-b07d-877e3a4c5cd7', on_delete=django.db.models.deletion.PROTECT, related_name='bo_location_visit', to='authentication.beatofficermodel'),
            preserve_default=False,
        ),
    ]
