# Generated by Django 4.2.3 on 2023-08-11 13:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0012_loactionvisitmodel_bo'),
    ]

    operations = [
        migrations.AddField(
            model_name='generalvisitmodel',
            name='situation',
            field=models.FloatField(default=5.0, validators=[django.core.validators.MaxValueValidator(10.0), django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AddField(
            model_name='personvisitmodel',
            name='situation',
            field=models.FloatField(default=5.0, validators=[django.core.validators.MaxValueValidator(10.0), django.core.validators.MinValueValidator(0.0)]),
        ),
    ]
