# Generated by Django 4.2.4 on 2023-08-03 10:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BeatOfficerModel',
            fields=[
                ('baseuser_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('service_number', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'beat_officer',
            },
            bases=('base.baseuser',),
        ),
        migrations.CreateModel(
            name='OfficerModel',
            fields=[
                ('baseuser_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('post', models.CharField(choices=[('SP', 'Superintendent of Police'), ('DYSP', 'Deputy Superintendent of Police'), ('PI', 'Police Inspector'), ('IGP', 'Inspector-General of Police')], max_length=50)),
                ('service_number', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'officer',
            },
            bases=('base.baseuser',),
        ),
    ]
