# Generated by Django 4.2.4 on 2023-08-02 11:25

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SellerModel',
            new_name='OfficerModel',
        ),
    ]
