# Generated by Django 4.2.4 on 2023-08-07 11:44

from django.conf import settings
import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0001_initial'),
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DistrictModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=50)),
                ('desc', models.TextField(blank=True, null=True)),
                ('contact_no', models.CharField(blank=True, max_length=50, null=True)),
                ('region', django.contrib.gis.db.models.fields.PolygonField(srid=4326)),
                ('office_address', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'district',
            },
        ),
        migrations.CreateModel(
            name='OfficerModel',
            fields=[
                ('baseuser_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('post', models.CharField(choices=[('SP', 'Superintendent of Police'), ('DYSP', 'Deputy Superintendent of Police'), ('PI', 'Police Inspector'), ('IGP', 'Inspector-General of Police')], max_length=50)),
            ],
            options={
                'db_table': 'officer',
            },
            bases=('base.baseuser',),
        ),
        migrations.CreateModel(
            name='SubDivisionModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=50)),
                ('desc', models.TextField(blank=True, null=True)),
                ('contact_no', models.CharField(blank=True, max_length=50, null=True)),
                ('region', django.contrib.gis.db.models.fields.PolygonField(srid=4326)),
                ('office_address', models.TextField(blank=True, null=True)),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_divisions', to='authentication.districtmodel')),
                ('dysp', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='authentication.officermodel')),
            ],
            options={
                'db_table': 'sub_division',
            },
        ),
        migrations.CreateModel(
            name='StateModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=50)),
                ('desc', models.TextField(blank=True, null=True)),
                ('contact_no', models.CharField(blank=True, max_length=50, null=True)),
                ('region', django.contrib.gis.db.models.fields.PolygonField(srid=4326)),
                ('office_address', models.TextField(blank=True, null=True)),
                ('igp', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='authentication.officermodel')),
            ],
            options={
                'db_table': 'state',
            },
        ),
        migrations.CreateModel(
            name='PoliceStationModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=50)),
                ('desc', models.TextField(blank=True, null=True)),
                ('contact_no', models.CharField(blank=True, max_length=50, null=True)),
                ('region', django.contrib.gis.db.models.fields.PolygonField(srid=4326)),
                ('office_address', models.TextField(blank=True, null=True)),
                ('pi', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='authentication.officermodel')),
                ('sub_division', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='police_stations', to='authentication.subdivisionmodel')),
            ],
            options={
                'db_table': 'police_station',
            },
        ),
        migrations.AddField(
            model_name='districtmodel',
            name='sp',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='authentication.officermodel'),
        ),
        migrations.AddField(
            model_name='districtmodel',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='districts', to='authentication.statemodel'),
        ),
        migrations.CreateModel(
            name='BeatOfficerModel',
            fields=[
                ('baseuser_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('beat_area', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='bo_of_ba', to='authentication.beatareamodel')),
                ('police_station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Police_Station_BOs', to='authentication.policestationmodel')),
            ],
            options={
                'db_table': 'beat_officer',
            },
            bases=('base.baseuser',),
        ),
        migrations.AddField(
            model_name='beatareamodel',
            name='police_station',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='beats', to='authentication.policestationmodel'),
        ),
    ]
