# Generated by Django 4.2.4 on 2023-08-11 05:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beatofficermodel',
            name='beat_area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bo_of_ba', to='authentication.beatareamodel'),
        ),
        migrations.AlterField(
            model_name='districtmodel',
            name='sp',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='authentication.officermodel'),
        ),
        migrations.AlterField(
            model_name='policestationmodel',
            name='pi',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='authentication.officermodel'),
        ),
        migrations.AlterField(
            model_name='statemodel',
            name='igp',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='authentication.officermodel'),
        ),
        migrations.AlterField(
            model_name='subdivisionmodel',
            name='dysp',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='authentication.officermodel'),
        ),
    ]
