# Generated by Django 4.2.4 on 2023-08-03 04:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_rename_sellermodel_officermodel'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='beatofficermodel',
            table='beat_officer',
        ),
        migrations.AlterModelTable(
            name='officermodel',
            table='officer',
        ),
    ]
