# Generated by Django 4.2.4 on 2023-08-04 05:07

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='officermodel',
            managers=[
                ('admin_objects', django.db.models.manager.Manager()),
            ],
        ),
    ]
