# Generated by Django 4.2.4 on 2023-08-11 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_alter_beatofficermodel_beat_area_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='officermodel',
            options={'permissions': [('guardian_view_location', 'obj level view location permission')]},
        ),
    ]
