# Generated by Django 4.2.4 on 2023-08-12 06:19

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_alter_officermodel_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='beatareamodel',
            old_name='region',
            new_name='area',
        ),
        migrations.RenameField(
            model_name='districtmodel',
            old_name='region',
            new_name='area',
        ),
        migrations.RenameField(
            model_name='policestationmodel',
            old_name='region',
            new_name='area',
        ),
        migrations.RenameField(
            model_name='statemodel',
            old_name='region',
            new_name='area',
        ),
        migrations.RenameField(
            model_name='subdivisionmodel',
            old_name='region',
            new_name='area',
        ),
        migrations.RemoveField(
            model_name='districtmodel',
            name='office_address',
        ),
        migrations.RemoveField(
            model_name='policestationmodel',
            name='office_address',
        ),
        migrations.RemoveField(
            model_name='statemodel',
            name='office_address',
        ),
        migrations.RemoveField(
            model_name='subdivisionmodel',
            name='office_address',
        ),
        migrations.CreateModel(
            name='TempAssignmentModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('assigned_to', models.CharField(max_length=50)),
                ('officer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='officer_temp_assignment', to='authentication.officermodel')),
            ],
            options={
                'db_table': 'officer_temp_assignmet',
            },
        ),
        migrations.CreateModel(
            name='AddEditModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('approval_type', models.CharField(choices=[('LOCATION', 'Location'), ('PERSON', 'Person')], max_length=12)),
                ('approval_status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default=('PENDING', 'Pending'), max_length=12)),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('category', models.CharField(blank=True, max_length=50, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='approvals')),
                ('incharge_name', models.CharField(blank=True, max_length=50, null=True)),
                ('incharge_contact', models.CharField(blank=True, max_length=50, null=True)),
                ('incharge_description', models.CharField(blank=True, max_length=50, null=True)),
                ('BO', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='bo_req', to='authentication.beatofficermodel')),
            ],
            options={
                'db_table': 'approval_requests',
            },
        ),
    ]
