# Generated by Django 4.2.4 on 2023-08-12 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_addeditmodel_chaing_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AddEditModel',
        ),
    ]
