# Generated by Django 4.2.4 on 2023-08-16 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0007_delete_addeditmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='beatofficermodel',
            name='tid',
            field=models.CharField(default='abc', max_length=10),
            preserve_default=False,
        ),
    ]
