# Generated by Django 4.2.4 on 2023-08-07 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='baseuser',
            name='dob',
            field=models.DateField(blank=True, null=True),
        ),
    ]
