# Generated by Django 4.2.3 on 2023-08-07 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='baseuser',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to='profile'),
        ),
    ]
