# Generated by Django 4.2.3 on 2023-08-07 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_baseuser_profile_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='baseuser',
            name='dob',
            field=models.DateField(blank=True, null=True),
        ),
    ]
