# Generated by Django 4.2.3 on 2023-08-08 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_baseuser_dob'),
    ]

    operations = [
        migrations.AddField(
            model_name='baseuser',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
    ]
