# Generated by Django 4.2.4 on 2023-08-11 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_alter_baseuser_service_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baseuser',
            name='service_number',
            field=models.CharField(max_length=10),
        ),
    ]
