# Generated by Django 4.2.3 on 2023-08-19 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_alter_baseuser_service_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baseuser',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='baseuser',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
